### ISSUE TITLE
The question of the model parameters

### ISSUE THREAD

**Issue by CVHW** [hanchenchen/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch#1]
Thank you for releasing the code(PyTorch version). I have tested the parameters of the model (ARB_None) which is up to 7.15M. This result is inconsistent with the paper records (1.9M). Have you ever tested this metric?

**Comment by hanchenchen** [comment]
Some kernel_size and paddings are corrected. Now the number of trainable parameters is 1945122.
