### ISSUE TITLE
Output 0 of ReshapeAliasBackward0 is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

### ISSUE THREAD

**Issue by wefwwef4** [hanchenchen/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch#4]
Traceback (most recent call last):
  File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model\__init__.py", line 243, in <module>
    y = model(x)
  File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model\__init__.py", line 214, in forward
    x = self.dense3(x)
  File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model\__init__.py", line 154, in forward
    inputs = self.arb[i](inputs)
  File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model\__init__.py", line 72, in forward
    augmented_conv = self.attention_aug(x)
  File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model\attention_augmentation2D.py", line 58, in forward
    flat_q, flat_k, flat_v, q, k, v = self.compute_flat_qkv(x, self.dk, self.dv, self.Nh)
  File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model\attention_augmentation2D.py", line 85, in compute_flat_qkv
    q *= dkh ** -0.5
RuntimeError: Output 0 of ReshapeAliasBackward0 is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

Process finished with exit code 1

**Comment by ZH3nGsQ** [comment]
> Traceback (most recent call last): File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model__init__.py", line 243, in y = model(x) File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model__init__.py", line 214, in forward x = self.dense3(x) File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model__init__.py", line 154, in forward inputs = self.arb[i](inputs) File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model__init__.py", line 72, in forward augmented_conv = self.attention_aug(x) File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\container.py", line 217, in forward input = module(input) File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model\attention_augmentation2D.py", line 58, in forward flat_q, flat_k, flat_v, q, k, v = self.compute_flat_qkv(x, self.dk, self.dv, self.Nh) File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model\attention_augmentation2D.py", line 85, in compute_flat_qkv q *= dkh ** -0.5 RuntimeError: Output 0 of ReshapeAliasBackward0 is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.
> 
> Process finished with exit code 1

hi! Did you solve the problem? How did you solve it?

**Comment by wefwwef4** [comment]
> > Traceback (most recent call last): File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model__init__.py", line 243, in y = model(x) File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model__init__.py", line 214, in forward x = self.dense3(x) File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model__init__.py", line 154, in forward inputs = self.arb[i](inputs) File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model__init__.py", line 72, in forward augmented_conv = self.attention_aug(x) File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\container.py", line 217, in forward input = module(input) File "C:\Users\90458\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model\attention_augmentation2D.py", line 58, in forward flat_q, flat_k, flat_v, q, k, v = self.compute_flat_qkv(x, self.dk, self.dv, self.Nh) File "C:\Mywork\pythonproject\Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main\model\attention_augmentation2D.py", line 85, in compute_flat_qkv q *= dkh ** -0.5 RuntimeError: Output 0 of ReshapeAliasBackward0 is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.
> > Process finished with exit code 1
> 
> hi! Did you solve the problem? How did you solve it?

>This should be an issue with the PyTorch version, just change the in place operation to normal addition
